sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - secure: "x16SKzADyFDPdh6UYxwMiA3bHQBwnyS8QFd3Cj6IEJs8U5QP09I1v8RUkYP3hE4t5c+zFupB4ev+WcK+W5uhO0nQ7S88x+TQ4LW3bIMhICCyIXk6rLCXkSfs1qojjG9j33/r0UZ8D0Sxph4gPH4gUa2uN+pIWU/Rl5+pZ28C/JPPx3VyGCaOxLE++/IdtG+Rua1f744mnz5+VFewYbQVMkz0Q+be1TnpMAUovZti/X0g2T8rutMDZaIHPpd4Z6pUT7t4l0FcwYq/FWxuDyTWk4HykNQSONrsmTJL6akHEEiu02rnld90ExSzw80ip0R42YP4DnCy7IdXNaxUeQDKw1w84QvvYOoa+Wv3YFAKarbso7EaSnRGuixHtfQFOgYh+G0cyVZPsy4bok8kcpZCc/74Ai75I4xKW62euBzvS+z3O0CFwbsQfUrjkEEEvHQqNCaM1np4TsqaSm4Y8qEbllso/7lH3++eVWgMNSTXdCPu1OyfMGPRyVWasoqa+zbuoEDxQps44F7MXCoQ3fZlz0aEyLab4mz+arZkoV4nPipJv6Vly+FFMb0Xz9ggeTMm4beOZInr9/fsmbQ2SuiJRSKjtuFVa0D0ySSJcjGexdTSL93mInFuHAuqL39bgBPbrHNVUsAixllrN/rx8RaseC8RP8Oga/k4/LKMKw0Cw9Q=" # DOCKER_HUB_TOKEN
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
# notify Docker Hub to make a new build || try 1
- >
  [ "$TRAVIS_BRANCH" == "master" ]
  && curl -X POST -H "Content-Type: application/json"
  --data '{"docker_tag_name": "latest"}'
  https://registry.hub.docker.com/u/allinse/allinse-project/trigger/$DOCKER_HUB_TOKEN/

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG
  - export CONFIG=allinse-docker/config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # EUREKA
  - export EUREKA=allinse-docker/eureka
  - docker build -t $EUREKA:$COMMIT ./eureka
  - docker tag $EUREKA:$COMMIT $EUREKA:$TAG
  - docker push $EUREKA

  # GATEWAY
  - export GATEWAY=allinse-docker/gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # OAUTH SERVICE
  - export OAUTH_SERVICE=allinse-docker/oauth-service
  - docker build -t $OAUTH_SERVICE:$COMMIT ./oauth-service
  - docker tag $OAUTH_SERVICE:$COMMIT $OAUTH_SERVICE:$TAG
  - docker push $OAUTH_SERVICE

  # PERSONNEL
  - export PERSONNEL=allinse-docker/personnel
  - docker build -t $PERSONNEL:$COMMIT ./personnel
  - docker tag $PERSONNEL:$COMMIT $PERSONNEL:$TAG
  - docker push $PERSONNEL