sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - secure: "BJgY2wYwoWuIuZBd7q9Bp+uDv/9egYLlQkJ4dFgWXXnzRecrSaVaUGRj6h86nhIXvwPuPjUbW717CTlCTkdhFrtNjOc1mze5w9v8T6LrxnysIy7i+PokEuRzwilCOJF6RpZzB/POmBlN1DHJ0TqD/5OO2QrHz/lVhC6Hf00mA+Hqqo8KrzEH0xY3s8RHbL7dJPLgWqFF8WDPG0nvfMAGFFL+pkNzYoIyxlwlft+JK3Gn+NyAQT9pDs8efSv3FWJoeNy5i45KfJbS4E+tizKOgUECQQd1RBV9MwJqlhyNs4QeO6lc+cHhpG8oQ3MxMMCjYpqGFK/6MkIwywh5HTkvIQbX7Gz+EMK6FO6NTco6MJZKVHnaXiO7ntyNQJw+Ztai83EuXP7lFqqYjI+vSqKb8UX8R6gqPvuazg16MZw9MoFQjtYvh3rarL05tUkc7sYkY+rZDuyTDpCf8a27qTqPjhB0m19cIEPUNQJ4XAr5XmNmtDWMxmhmV/xuEoFVFKSFvWwZ5W1k2VKKsB3mIW4y1sL5nwazR68WdmhLJ/EV3ZUI2A1RwdGgxsW1PuGUiwEisTMzeydjyQuH4FyBymuvgdZmtb+SkAY/AYr2DV+0B62ifRdIj7KGvZCjVnIoYQgjKOGPGieSRfgZzoR5Py1zyFyBRX4MdarHOsnD124WWwY=" # DOCKER_EMAIL
    - secure: "OL1O2d46CPnCCIOE1DQYJUdWsmP+EPgMcv3xTHdxk7TV5uV8//3qZfBKGgf2rOoZV9FdXmD81/GJQ3f2S17tvVSGnX1oOmriqaqCDGHHhuV5Mvm9/X9KeDKTPtDcD367r3jz/m80/F8Mir7Hb9pi+Bu6rLkXAtZhb5XlBjJ6KyG6/v5JlpG1rgxQ2zTS+D7fQ7UN0WI8zFxWOFtcJ/KrfMHyWTCLhgTbQttn6SmMmsegElALZ5wOhf7Tsu4qGCthQWJJ+DqX2NQCazsLlz1dgDW/fgdBUrjdYZwy5Qdg5nP/dP5JObSIepVo+zhYgnncuv6mKUtoatIyWJ4aYHyMGIDyXOmBEVvwdoX6gv85P8/BWoHsEKCeL7bmR7dT2m1hlu4TqejzGF/yzpKSFvZC7cd6e+8ihsdToOwzAGO6snmC+vlewwHjba5wwKdFt3tyWMITrhrwmFWALv4w2KaKYDA/TYQ7/ipZXMJIyn4SKjPKOcIrjkdlPYDNMqLaZnf5ruWV/HppenxrqEUwCASR4QryZIhSB9kXjmcG2bFwkocDT3C9EvIKnp2z4MSnekKeUmNHwuuUmYwhCFzv2G5imDWT3UYHlN8SYOq95/SEXvGUZHDQ2RLf/vDOAjPycUbTk5j/OO91p0w5TAWHf/W10ASr8wsLOKX080iMcKawC9E=" # DOCKER_USER
    - secure: "AWO4dXTTSSs4OkPRD3bpWaOh6fqQjIPeQYWM7vujrCo69bHo/yRhWxeG5YYgid4s0NOPY4vZSls5GQr5jihWiMQB9aIQUj3WNATDc52ZRkp4aNqBqsjUSbHY3GWg8tDVbiZqRjLQt+8inIm9eEZf9G3xyadJDD+uEHRPG7g5qXjMZmgbkMZVN03YQmfcvhGyynPVAbrIn6sTAYjbjAVbgYusbtHGZt42NsFpSJt4s/uOAWXZcKAMkPCtnnppW+7HZkBXWQiB1MfdenTJZmcIkrMYmYZE9bSUKRY9JjHv4NPvkj3dBZpaN1k4RRY/D6CsNpZVgs19pBshomW4H0XwsQPCg0Q9mKFpKQfyiwaflQHqeuUqPisa8YYQaLtBcAdCzxcs6ib+4to1j14xV30fbJbBw4GKjqeLZah/IGW7EId/RGojns1BnfV92fQK3/6ANL0j2oE3NK6Vx5z1GtxWV5WLyMUniGUX3J2JjfhZ/Ev5LcEv5vASQjEv6ZxiDC4hNiIRwOMqkdGDXo8CrAu4uM0Ob1KBVE+IebSHqNcrZ+W0N1RwgN/OubhE6G1gEErpqvmQut8BH86CzNQGFBt/O8MhVs72LWajYzdIWIepEktvy2VoKUpPH1EeLgJeRKmOfubRsoAIpGTvAbeOgjKsWFMQE+csU1wiZf+bbipkps0=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG
  - export CONFIG=allinse-project/config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # EUREKA
  - export EUREKA=allinse-project/eureka
  - docker build -t $EUREKA:$COMMIT ./eureka
  - docker tag $EUREKA:$COMMIT $EUREKA:$TAG
  - docker push $EUREKA

  # GATEWAY
  - export GATEWAY=allinse-project/gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # OAUTH SERVICE
  - export OAUTH_SERVICE=allinse-project/oauth-service
  - docker build -t $OAUTH_SERVICE:$COMMIT ./oauth-service
  - docker tag $OAUTH_SERVICE:$COMMIT $OAUTH_SERVICE:$TAG
  - docker push $OAUTH_SERVICE

  # PERSONNEL
  - export PERSONNEL=allinse-project/personnel
  - docker build -t $PERSONNEL:$COMMIT ./personnel
  - docker tag $PERSONNEL:$COMMIT $PERSONNEL:$TAG
  - docker push $PERSONNEL