version: '2'
services:
  config:
    image: allinse/config
    restart: always
    ports:
          - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  eureka:
    image: allinse/eureka
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: allinse/gateway
    restart: always
    ports:
      - 4000:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  oauth-service:
    image: allinse/oauth-service
    restart: always
    ports:
          - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  personnel:
    image: allinse/personnel
    restart: always
    ports:
      - 6000:6000
    logging:
      options:
        max-size: "10m"
        max-file: "10"